---
logging:
  log_freq: 50
  log_level: info
  log_dir: /home/wang_yi/la/tensorboard_log
  n_val_imgs: 5
data:
  DSM: /home/wang_yi/la/cGAN-light/test_output/result_dsm_all #train refined dsm
  MASK: /home/wang_yi/la/dataset/BMdirectFromLOD2filled_roi_GEOKOL #building mask for norm-loss
  Ortho: /home/wang_yi/la/dataset/WV-1/O.3 #orthophoto(pan)
  Out: /home/wang_yi/la/dataset/LOD2filled_wth_DGM_roi_intrp_GEOKOLref #GroundTruth DSM
  Edges: /home/wang_yi/la/MakeGT/building_edges_2c_roi_aligned_nobil_b0
  Instances: /home/wang_yi/la/dataset/building_instances_roi_aligned # GT building instances (new!)
  roi_train: [0, 0, 30733, 40000]
  roi_val: [0, 40000, 30733, 5999]
  roi_test: [30733, 0, 4950, 45999] #[30733, 0, 4950, 5999]
  roi_all: [0, 0, 35683, 45999]

minQuantile: 0.01
heightRange: 200

patience: 7



